name = "My-Modpack"
author = "WingChunWong"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5305e7c31f71cc6a3939999a580c035d2cca57f7b03ac8d79b379cce4e45bdbc"

[versions]
fabric = "0.18.6"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.20.1", "1.21.1"]
