name = "My Modpack"
author = "WingChunWong"
version = "1.0.0"
description = "A modpack for selfuse"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b9ad3f00f483a96310bc6af3d4154ffb4489d689f66163c87eaf5b6d04ac00c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
