name = "My-Modpack"
author = "WingChunWong"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7749a67c016c36e5b4b8e72652a8795415ae5c0583572be4dbddf196fd6e53e9"

[versions]
fabric = "0.18.6"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.20.1", "1.21.1"]
