#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 07 13:50:23 HKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=SEUS PTGI HRR Test 2.1 GFME 1.20.zip
