name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build mrpack
        run: ./srdk.exe build

      - name: Build offline mrpack
        run: ./srdk.exe build_offline

      - uses: actions/upload-artifact@v7
        with:
          name: modpack
          path: build/*.mrpack
          if-no-files-found: error