name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build mrpack
        run: ./srdk.exe build

      - name: Build offline mrpack
        run: ./srdk.exe build_offline

      - uses: softprops/action-gh-release@v2
        with:
          files: build/*.mrpack
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}